# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
arr1=np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()

arr3=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape,arr1.ndim,arr1.dtype,arr1.size,type(arr1)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [14]:
# Attributes of 2-dimensional array
arr2.shape,arr2.ndim,arr2.dtype,type(arr2)

((2, 3), 2, dtype('int64'), numpy.ndarray)

In [19]:
# Attributes of 3-dimensional array
arr3.shape,arr3.ndim,arr3.dtype,type(arr3)

((2, 2, 3), 3, dtype('int64'), numpy.ndarray)

In [20]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

In [22]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
# Create an array within a range of 0 and 100 with step 3
range_array=np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [25]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array1=np.random.randint(0,10,size=(7,2))
random_array1

array([[8, 8],
       [3, 9],
       [3, 5],
       [9, 2],
       [3, 4],
       [7, 1],
       [2, 4]], dtype=int32)

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array2=np.random.random((3,5))
random_array2

array([[0.09109992, 0.46039803, 0.20766128, 0.57844305, 0.84100609],
       [0.19382657, 0.1844223 , 0.26768065, 0.7314784 , 0.83077345],
       [0.95373392, 0.04196224, 0.62676986, 0.0365679 , 0.56016406]])

In [28]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array3=np.random.randint(0,10,size=(4,6))
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [34]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array4=np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
a=np.unique(random_array4)
#a
random_array4

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3],
       [1, 3, 5, 3, 1, 5, 7]], dtype=int32)

In [35]:
# Find the 0'th index of the latest array you created
random_array4[0,0]

np.int32(9)

In [37]:
# Get the first 2 rows of latest array you created
random_array4[:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]], dtype=int32)

In [38]:
# Get the first 2 values of the first 2 rows of the latest array
random_array4[:2,:2]

array([[9, 7],
       [7, 8]], dtype=int32)

In [48]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(seed=1)
random_array5=np.random.randint(0,10,size=(3,5))
ones2=np.ones((3,5))


In [49]:
random_array5

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4]], dtype=int32)

In [50]:
ones2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
# Add the two arrays together
random_array5+ones2

array([[ 6.,  9., 10.,  6.,  1.],
       [ 1.,  2.,  8.,  7., 10.],
       [ 3.,  5.,  6.,  3.,  5.]])

In [52]:
# Create another array of ones of shape (5, 3)
ones3=np.ones((5,3))
ones3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
# Try add the array of ones and the other most recent array together
# random_array5+ones3 #Don't work, because of the discrepancy 
random_array5.T+ones3

array([[ 6.,  1.,  3.],
       [ 9.,  2.,  5.],
       [10.,  8.,  6.],
       [ 6.,  7.,  3.],
       [ 1., 10.,  5.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

##### My Ans:
 We have to get the transpose of the random_array5 or ones, because of the
 dimensional discrepancies.

In [55]:
# Create another array of ones of shape (3, 5)
ones4=np.ones((3,5))
ones4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
# Subtract the new array of ones from the other most recent array
random_array5-ones4

array([[ 4.,  7.,  8.,  4., -1.],
       [-1.,  0.,  6.,  5.,  8.],
       [ 1.,  3.,  4.,  1.,  3.]])

In [57]:
# Multiply the ones array with the latest array
random_array5 * ones4

array([[5., 8., 9., 5., 0.],
       [0., 1., 7., 6., 9.],
       [2., 4., 5., 2., 4.]])

In [59]:
# Take the latest array to the power of 2 using '**'
random_array5 ** 2

array([[25, 64, 81, 25,  0],
       [ 0,  1, 49, 36, 81],
       [ 4, 16, 25,  4, 16]], dtype=int32)

In [60]:
# Do the same thing with np.square()
np.square(random_array5)

array([[25, 64, 81, 25,  0],
       [ 0,  1, 49, 36, 81],
       [ 4, 16, 25,  4, 16]], dtype=int32)

In [61]:
# Find the mean of the latest array using np.mean()
np.mean(random_array5)

np.float64(4.466666666666667)

In [62]:
# Find the maximum of the latest array using np.max()
np.max(random_array5)

np.int32(9)

In [63]:
# Find the minimum of the latest array using np.min()
np.min(random_array5)

np.int32(0)

In [65]:
# Find the standard deviation of the latest array
np.std(random_array5)

np.float64(2.9181424837652385)

In [66]:
# Find the variance of the latest array
np.var(random_array5)

np.float64(8.515555555555556)

In [67]:
# Reshape the latest array to (3, 5, 1)
random_array5.reshape(3,5,1)

array([[[5],
        [8],
        [9],
        [5],
        [0]],

       [[0],
        [1],
        [7],
        [6],
        [9]],

       [[2],
        [4],
        [5],
        [2],
        [4]]], dtype=int32)

In [68]:
# Transpose the latest array
random_array5.T

array([[5, 0, 2],
       [8, 1, 4],
       [9, 7, 5],
       [5, 6, 2],
       [0, 9, 4]], dtype=int32)

What does the transpose do?
##### My Ans:
Change the columns and rows with each other.

In [70]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(seed=2)
r_arr_1=np.random.randint(0,10,size=(3,3))
r_arr_2=np.random.randint(0,10,size=(3,2))


In [71]:
# Perform a dot product on the two newest arrays you created
np.dot(r_arr_1,r_arr_2)

array([[ 90, 124],
       [ 69, 106],
       [ 28,  45]], dtype=int32)

In [74]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(seed=3)
r_arr_3=np.random.randint(0,10,size=(4,3))
r_arr_4=np.random.randint(0,10,size=(4,3))

In [76]:
r_arr_3

array([[8, 9, 3],
       [8, 8, 0],
       [5, 3, 9],
       [9, 5, 7]], dtype=int32)

In [77]:
r_arr_4

array([[6, 0, 4],
       [7, 8, 1],
       [6, 2, 2],
       [1, 3, 5]], dtype=int32)

In [80]:
# Perform a dot product on the two newest arrays you created
np.dot(r_arr_3,r_arr_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

My ans:
We have to reshape array.

In [81]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(r_arr_3,r_arr_4.T)

array([[ 60, 131,  72,  50],
       [ 48, 120,  64,  32],
       [ 66,  68,  54,  59],
       [ 82, 110,  78,  59]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [82]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
r_arr_5=np.random.randint(0,10,size=(2,3))
r_arr_6=np.random.randint(0,10,size=(2,3))

In [83]:
# Compare the two arrays with '>'
r_arr_5>r_arr_6

array([[ True, False,  True],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

My ans:

Compare the elements and create new array of the results which type of bool.

In [84]:
# Compare the two arrays with '>='
r_arr_5>=r_arr_6

array([[ True, False,  True],
       [ True,  True, False]])

In [85]:
# Find which elements of the first array are greater than 7
r_arr_4>7

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [87]:
# Which parts of each array are equal? (try using '==')
r_arr_6 == r_arr_5

array([[False, False, False],
       [False, False, False]])

In [88]:
# Sort one of the arrays you just created in ascending order
np.sort(r_arr_5)

array([[1, 8, 8],
       [1, 7, 8]], dtype=int32)

In [91]:
r_arr_5

array([[8, 1, 8],
       [7, 8, 1]], dtype=int32)

In [94]:
r_arr_7=np.random.randint(0,100,size=(2,3))
r_arr_7

array([[37, 56, 56],
       [71, 37, 46]], dtype=int32)

In [95]:
np.argsort(r_arr_7)

array([[0, 1, 2],
       [1, 2, 0]])

In [89]:
# Sort the indexes of one of the arrays you just created
np.argsort(r_arr_5)

array([[1, 0, 2],
       [2, 0, 1]])

In [96]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(r_arr_7)

np.int64(3)

In [97]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(r_arr_7)

np.int64(0)

In [98]:
r_arr_7

array([[37, 56, 56],
       [71, 37, 46]], dtype=int32)

In [100]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(r_arr_7,axis=1)

array([1, 0])

In [101]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(r_arr_7,axis=0)

array([1, 0, 0])

In [106]:
# Create an array of normally distributed random numbers
np.random.normal(loc=10,scale=0.11,size=10)
#loc=mean
#scale=standard deviation
#size=size

array([ 9.97828439, 10.19521095,  9.92577997, 10.01656786, 10.01682403,
        9.88293852, 10.04817413, 10.21328763,  9.8872576 , 10.09892723])

In [107]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.